services:
  app:
    build: .
    container_name: reviewer-x
    restart: unless-stopped
    ports:
      - "3002:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/reviewer-x
    volumes:
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=reviewer-x
    command: ["--quiet", "--logpath", "/dev/null"]

volumes:
  mongo-data:
    name: reviewer-x-mongo-data
