services:
  app:
    build: .
    container_name: reviewer-x
    restart: unless-stopped
    ports:
      - "3002:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - MY_SECRET=${MY_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - EMAIL_PROVIDER=${EMAIL_PROVIDER}
      - SECRET_ADMIN_TOKEN=${SECRET_ADMIN_TOKEN}
      - SUPER_USER_TOKEN=${SUPER_USER_TOKEN}
      - WEBSHARE_API_TOKEN=${WEBSHARE_API_TOKEN}
      - AUTH_ENCRYPTION_KEY=${AUTH_ENCRYPTION_KEY}
      - PROD_URL=${PROD_URL}
      - EMAIL_FOR_NOTIFICATION=${EMAIL_FOR_NOTIFICATION}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - EMAIL__APP_PASS=${EMAIL__APP_PASS}
      - SKU=${SKU}
      - KIND=${KIND}
      - RESOURCE_GROUP=${RESOURCE_GROUP}
      - LOCATION=${LOCATION}
      - AZURE_STORAGE_CONTAINER=${AZURE_STORAGE_CONTAINER}
      - AZURE_KEYVAULT=${AZURE_KEYVAULT}
      - AZURE_BLOB_SAS_SECRET=${AZURE_BLOB_SAS_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - COSMOS_DB_ENDPOINT=${COSMOS_DB_ENDPOINT}
      - COSMOS_DB_KEY=${COSMOS_DB_KEY}
      - COSMOS_DB_NAME=${COSMOS_DB_NAME}
      - COSMOS_CONTAINER_NAME=${COSMOS_CONTAINER_NAME}
      - AZURE_APIM_NAME=${AZURE_APIM_NAME}
      - AZURE_APIM_ENDPOINT=${AZURE_APIM_ENDPOINT}
      - AZURE_API_URL=${AZURE_API_URL}
      - PUPPETEER_EXECUTABLE_PATH=${PUPPETEER_EXECUTABLE_PATH}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}

    volumes:
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=reviewer-x
    command: ["--quiet", "--logpath", "/dev/null"]

volumes:
  mongo-data:
    name: reviewer-x-mongo-data
