name: deploy-to-heroku-pipline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Heroku Container Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ray-project-x
        run: |
          heroku container:push web --app ray-project-x

      - name: Release Docker container on Heroku
        run: |
          heroku container:release web --app ray-project-x

      - name: Check deployment logs
        run: heroku logs --tail --app ray-project-x
